CREATE OR REPLACE TABLE  `ci-datalake-dev.ci_dtlk_bqd_staging_dev_RNC.MAESTRO_GRADO_INSTRUCCION` 
(
  CODIGO_INSTRUCCION_XHIS               INT64,
  DESCRIPCION_INSTRUCCION_XHIS     STRING,
  CODIGO_INSTRUCCION_RNC                INT64,
  DESCRIPCION_INSTRUCCION_RNC     STRING
);


INSERT INTO `ci-datalake-dev.ci_dtlk_bqd_staging_dev_RNC.MAESTRO_GRADO_INSTRUCCION` 
(CODIGO_INSTRUCCION_XHIS, DESCRIPCION_INSTRUCCION_XHIS, CODIGO_INSTRUCCION_RNC, DESCRIPCION_INSTRUCCION_RNC)
VALUES
  (1,'[NINGUNA]',1,'Sin instrucci\'f3n')\
, (2,'NO ESPECIFICA',NULL,NULL)\
, (3,'NIDO',NULL,NULL)\
, (4,'PRIMARIA',4,'Primario')
, (5,'SECUNDARIA',5,'Secundario')
, (6,'CARRERA TECNICA',6,'Superior T\'e9cnica')
, (7,'CARRERA UNIVERSITARIA',7,'Superio Universitario')
, (8,'BACHILLERATO',NULL,NULL)\
, (9,'MAESTRIA',NULL,NULL)\
, (10,'DOCTORADO',NULL,NULL);\
