DECLARE p_start DATE DEFAULT '2020-01-01';
DECLARE p_end   DATE DEFAULT '2025-04-01';

-- Variables de trabajo por iteración
DECLARE FEC_INI STRING;
DECLARE FEC_FIN STRING;

-- INICIO FOR
FOR mm IN (
  SELECT
    m                                  AS fecha_ini,
    DATE_ADD(m, INTERVAL 1 MONTH)      AS fecha_fin
  FROM UNNEST(GENERATE_DATE_ARRAY(
         DATE_TRUNC(p_start, MONTH),
         DATE_TRUNC(p_end,   MONTH),INTERVAL 1 MONTH)) AS m ) DO

-- COMIENZO DE LOGICA

CREATE OR REPLACE TABLE `ci-datalake-dev.ci_dtlk_bqd_staging_dev_RNC.BASE_DIAGNOTICOS_RNC_TEST` AS
WITH
data_34 AS  ( SELECT codigo_cliente
                         ,ESTADIO AS ESTADIO_CLINICO 
                   FROM `ci-datalake-dev.ci_dtlk_bqd_staging_dev_RNC.FORM_HISTORIA_CLINICA_ONCOLOGICA` 
                   WHERE FORMAT_DATE('%Y%m', fecha_registro_form) BETWEEN FORMAT_DATE('%Y%m', mm.fecha_ini )  AND FORMAT_DATE('%Y%m', mm.fecha_ini )  
                   QUALIFY ROW_NUMBER() OVER (PARTITION BY codigo_cliente ORDER BY fecha_registro_form DESC) = 1 ),

data_diag as (
SELECT FORMAT_DATE('%Y%m', mm.fecha_ini ) AS CODMES
      ,a.DIAGNOSTICO_PK
      ,a.CODIGO_CLIENTE
      ,a.FECHA_APERTURA
      ,c.DESCRIPCION  AS ESTADO_DX
      ,b.ICD_COD      AS ICD_CIE10
      ,b.ICD_NOM      AS DIAGNOSTICO_DESC
      ,b.LOCALIZACION_ANATOMICA
      ,e.ESTADIO_CLINICO
     ,CASE WHEN ESTADIO_CLINICO = 'III' AND b.LOCALIZACION_ANATOMICA NOT IN ('CEREBRO','GENITALES MASCULINOS', 'HEMATO-LINFOIDES') THEN 'NO'
           WHEN ESTADIO_CLINICO IS NULL AND b.LOCALIZACION_ANATOMICA IN ('HEMATO-LINFOIDES') THEN 'SI'
           WHEN ESTADIO_CLINICO NOT IN ( 'III', 'IV' ) THEN 'NO'
           WHEN ESTADIO_CLINICO IS NULL THEN  'NO' ELSE 'SI' END METASTASIS
FROM `ci-datalake-prod.ci_dtlk_bqd_access_prod.xhis6_DIAGNOSTICO_acc` a
INNER JOIN `ci-datalake-dev.ci_dtlk_bqd_staging_dev_RNC.MAESTRO_CIE10_DIAGNOSTICOS` b ON a.ICD_PK = b.ICD_PK AND TRIM(b.aplica) = 'S'
INNER JOIN `ci-datalake-prod.ci_dtlk_bqd_access_prod.xhis6_DIAGNOSTICO_ESTADO_acc` c ON a.ESTADO_PK = c.ESTADO_PK
INNER JOIN `ci-datalake-prod.ci_dtlk_bqd_access_prod.xhis6_DIAGNOSTICO_MADUREZ_acc` d ON a.MADUREZ_PK = d.MADUREZ_PK  AND a.MADUREZ_PK = 2
LEFT JOIN data_34 e ON a.CODIGO_CLIENTE = e.codigo_cliente
WHERE FORMAT_DATE('%Y%m', a.FECHA_APERTURA)  BETWEEN FORMAT_DATE('%Y%m', mm.fecha_ini )  AND FORMAT_DATE('%Y%m', mm.fecha_ini )  
QUALIFY ROW_NUMBER() OVER (PARTITION BY a.CODIGO_CLIENTE, b.LOCALIZACION_ANATOMICA  ORDER BY a.FECHA_APERTURA ASC) = 1
ORDER BY 2,3 )

SELECT * FROM data_diag;



MERGE `ci-datalake-dev.ci_dtlk_bqd_staging_dev_RNC.BASE_DIAGNOTICOS_RNC_METASTAIS` a
USING (
SELECT * FROM `ci-datalake-dev.ci_dtlk_bqd_staging_dev_RNC.BASE_DIAGNOTICOS_RNC_TEST`  WHERE METASTASIS = 'SI'
) b ON a.CODIGO_CLIENTE = b.CODIGO_CLIENTE 

WHEN NOT MATCHED THEN
  INSERT ( CODMES, DIAGNOSTICO_PK,CODIGO_CLIENTE, FECHA_APERTURA, ESTADO_DX, ICD_CIE10, DIAGNOSTICO_DESC, LOCALIZACION_ANATOMICA,ESTADIO_CLINICO, METASTASIS )
  VALUES ( b.CODMES, b.DIAGNOSTICO_PK, b.CODIGO_CLIENTE, b.FECHA_APERTURA, b.ESTADO_DX, b.ICD_CIE10, b.DIAGNOSTICO_DESC, b.LOCALIZACION_ANATOMICA, b.ESTADIO_CLINICO, b.METASTASIS ); 


MERGE `ci-datalake-dev.ci_dtlk_bqd_staging_dev_RNC.BASE_DIAGNOTICOS_RNC22` a
USING (
SELECT * FROM `ci-datalake-dev.ci_dtlk_bqd_staging_dev_RNC.BASE_DIAGNOTICOS_RNC_TEST`  WHERE METASTASIS <> 'SI'
AND CODIGO_CLIENTE not in ( SELECT DISTINCT CODIGO_CLIENTE FROM `ci-datalake-dev.ci_dtlk_bqd_staging_dev_RNC.BASE_DIAGNOTICOS_RNC_METASTAIS`)
) b 
ON a.CODIGO_CLIENTE = b.CODIGO_CLIENTE
AND a.LOCALIZACION_ANATOMICA = b.LOCALIZACION_ANATOMICA
WHEN NOT MATCHED THEN
  INSERT ( CODMES, DIAGNOSTICO_PK,CODIGO_CLIENTE, FECHA_APERTURA, ESTADO_DX, ICD_CIE10, DIAGNOSTICO_DESC, LOCALIZACION_ANATOMICA,ESTADIO_CLINICO, METASTASIS )
  VALUES ( b.CODMES, b.DIAGNOSTICO_PK, b.CODIGO_CLIENTE, b.FECHA_APERTURA, b.ESTADO_DX, b.ICD_CIE10, b.DIAGNOSTICO_DESC, b.LOCALIZACION_ANATOMICA, b.ESTADIO_CLINICO, b.METASTASIS ); 


-- TERMINO LOGICA
END FOR;
