CREATE OR REPLACE TABLE `ci-analytics-dev.ci_rretuerto_bqd_business_dev.TB_MAESTRO_ETIQUETAS` (
  CAMPO_PK     INT64,
  CAMPO_DESC   STRING,
  CAMPO_FINAL  STRING
);

INSERT INTO `ci-analytics-dev.ci_rretuerto_bqd_business_dev.TB_MAESTRO_ETIQUETAS` (
  CAMPO_PK, CAMPO_DESC, CAMPO_FINAL
) VALUES
  (31, 'Logo Institucional', 'LOGO_INSTITUCIONAL'),
  (369, 'Usuario de Conexión', 'USUARIO_CONEXION'),
  (567, 'Parámetros Clínicos', 'PARAMETROS_CLINICOS'),
  (568, 'Aseguradora', 'ASEGURADORA'),
  (573, 'Médico del encuentro', 'MEDICO_ENCUENTRO'),
  (574, 'N° de colegiatura', 'N_COLEGIATURA'),
  (575, 'RNE', 'RNE'),
  (580, 'Centro', 'CENTRO'),
  (581, 'Dirección del Centro', 'DIRECCION_CENTRO'),
  (582, 'Encuentro', 'ENCUENTRO'),
  (584, 'Hora', 'HORA'),
  (586, 'Próxima cita', 'PROXIMA_CITA'),
  (587, 'Fecha Actual', 'FECHA_ACTUAL'),
  (588, 'Hora Actual', 'HORA_ACTUAL'),
  (589, 'Firma médico', 'FIRMA_MEDICO'),
  (597, 'Antecedentes Familiares', 'ANTECEDENTES_FAMILIARES'),
  (598, 'Antecedentes Personales', 'ANTECEDENTES_PERSONALES'),
  (599, 'Alergias', 'ALERGIAS'),
  (600, 'Factor Rh', 'FACTOR_RH'),
  (601, 'GS', 'GS'),
  (603, 'Estado Civil', 'ESTADO_CIVIL'),
  (604, 'Fecha Nacimiento', 'FECHA_NACIMIENTO'),
  (605, 'Religión', 'RELIGION'),
  (606, 'Sexo', 'SEXO'),
  (607, 'N° Documento', 'N_DOCUMENTO'),
  (608, 'Paciente', 'PACIENTE'),
  (609, 'N° HCl', 'N_HCI'),
  (612, 'Exámenes Auxiliares', 'EXAMENES_AUXILIARES'),
  (618, 'Descanso medico', 'DESCANSO_MEDICO'),
  (621, 'Interconsulta', 'INTERCONSULTA'),
  (622, 'Apetito', 'APETITO'),
  (623, 'Deposiciones', 'DEPOSICIONES'),
  (624, 'Orina', 'ORINA'),
  (625, 'Sed', 'SED'),
  (626, 'Sueño', 'SUENO'),
  (637, 'Fecha', 'FECHA'),
  (638, 'Tiempo de enfermedad', 'TIEMPO_ENFERMEDAD'),
  (640, 'Indicaciones Médicas', 'INDICACIONES_MEDICAS'),
  (654, 'Peticiones', 'PETICIONES'),
  (659, 'Especificar', 'ESPECIFICAR'),
  (660, 'Genérico', 'GENERICO'),
  (661, 'Tipo de Ingreso', 'TIPO_INGRESO'),
  (665, 'Notas de enfermería', 'NOTAS_ENFERMERIA'),
  (674, 'Motivo de Hospitalización', 'MOTIVO_HOSPITALIZACION'),
  (675, 'Lateralidad', 'LATERALIDAD'),
  (678, 'Observaciones', 'OBSERVACIONES'),
  (689, 'Diagnóstico del Encuentro', 'DIAGNOSTICO_ENCUENTRO'),
  (692, 'Plan de trabajo', 'PLAN_TRABAJO'),
  (694, 'Servicio que Deriva2', 'SERVICIO_DERIVA2'),
  (708, 'Firma Licenciado', 'FIRMA_LICENCIADO'),
  (778, 'Examen Clínico2', 'EXAMEN_CLINICO2'),
  (798, 'Medicamentos', 'MEDICAMENTOS'),
  (930, 'Paridad', 'PARIDAD'),
  (931, 'Edad de Menarquia', 'EDAD_MENARQUIA'),
  (932, '1RS', '1RS'),
  (933, 'MAC', 'MAC'),
  (934, 'Andria', 'ANDRIA'),
  (935, 'Ult PAP', 'ULT_PAP'),
  (936, 'Resultado PAP', 'RESULTADO_PAP'),
  (937, 'Ult Mamografia', 'ULT_MAMOGRAFIA'),
  (939, 'Antedecentes Gineco-obstétricos', 'ANTECEDENTES_GINECO_OBSTETRICOS'),
  (940, 'Gestaciones', 'GESTACIONES'),
  (953, 'EVA ambulatorio', 'EVA_AMBULATORIO'),
  (958, 'anamnesis_2', 'ANAMNESIS2'),
  (969, 'Motivo de consulta SQL RTF', 'MOTIVO_CONSULTA_SQL_RTF'),
  (982, 'Periodo de enfermedad_Emergencia', 'PERIODO_ENFERMEDAD_EMERGENCIA'),
  (988, 'Persona de contacto', 'PERSONA_CONTACTO'),
  (1004, 'Motivo de egreso', 'MOTIVO_EGRESO'),
  (1005, 'Condición del paciente', 'CONDICION_PACIENTE'),
  (1006, 'UPSS destino', 'UPSS_DESTINO'),
  (1007, 'Servicio Destino', 'SERVICIO_DESTINO'),
  (1008, 'resultado Mamografia', 'RESULTADO_MAMOGRAFIA'),
  (1024, 'Destino2L', 'DESTINO2L'),
  (1028, 'Evolucion2', 'EVOLUCION2'),
  (1032, 'Examen mamas EC 2', 'EXAMEN_MAMAS_EC2'),
  (1034, 'Examen cervix EC', 'EXAMEN_CERVIX_EC'),
  (1036, 'Anamnesis_Exploracion', 'ANAMNESIS_EXPLORACION'),
  (1037, 'Edad año-mes-dia', 'EDAD_ANO_MES_DIA'),
  (1054, 'N° de colegiatura Usuario Conexion', 'N_COLEGIATURA_USUARIO_CONEXION'),
  (1059, 'Escala Glasgow', 'ESCALA_GLASGOW'),
  (1163, 'Ult PAP', 'ULT_PAP_2'),
  (1173, 'N° de Cama', 'N_CAMA'),
  (1187, 'Downton Extraido EC', 'DOWNTON_EXTRAIDO_EC'),
  (1188, 'Hora de Termino de quimioterapia', 'HORA_TERMINO_QUIMIOTERAPIA'),
  (1189, 'Nombre de Esquema Terapeútico', 'NOMBRE_ESQUEMA_TERAPEUTICO'),
  (1195, 'Permeabilidad de la via', 'PERMEABILIDAD_VIA'),
  (1197, 'Hora de Inicio de Quimioterapia', 'HORA_INICIO_QUIMIOTERAPIA'),
  (1198, 'Ambito', 'AMBITO'),
  (1200, 'Via de administración Quimioterapia', 'VIA_ADMINISTRACION_QUIMIOTERAPIA'),
  (1210, 'Modalidad de Cirugía', 'MODALIDAD_CIRUGIA'),
  (1214, 'Conteo de Gasas', 'CONTEO_GASAS'),
  (1215, 'Conteo de Instrumental', 'CONTEO_INSTRUMENTAL'),
  (1216, 'Patología', 'PATOLOGIA'),
  (1217, 'Biopsia por congelación', 'BIOPSIA_CONGELAMIENTO'),
  (1218, 'Cultivos', 'CULTIVOS'),
  (1219, 'Se informó a familiares', 'SE_INFORMO_FAMILIARES'),
  (1223, 'Servicio que deriva', 'SERVICIO_DERIVA'),
  (1225, 'Tiempo de Enfermedad', 'TIEMPO_ENFERMEDAD_1'),
  (1228, 'Tratamiento Recibido', 'TRATAMIENTO_RECIBIDO'),
  (1230, 'Evolución al Alta', 'EVOLUCION_ALTA'),
  (1231, 'Estancia', 'ESTANCIA'),
  (1232, 'Motivo de Egreso', 'MOTIVO_EGRESO'),
  (1233, 'Condición de Alta', 'CONDICION_ALTA'),
  (1235, 'Causa de Mortalidad', 'CAUSA_MORTALIDAD'),
  (1236, 'Necropsia', 'NECROPSIA'),
  (1261, 'Fecha de ingreso', 'FECHA_INGRESO'),
  (1263, 'Dx del encuentro', 'DX_ENCUENTRO'),
  (1314, 'Quirófano 2', 'QUIROFANO2'),
  (1355, 'Hora de ingreso', 'HORA_INGRESO'),
  (1357, 'Observaciones', 'OBSERVACIONES_2'),
  (1362, 'N° de días', 'N_DIAS'),
  (1377, 'Especificar', 'ESPECIFICAR'),
  (1552, 'Antedecentes Quirúrgicos', 'ANTECEDENTES_QUIRURGICOS'),
  (1576, 'Diagnóstico de ingreso', 'DIAGNOSTICO_INGRESO'),
  (1582, 'Complicaciones', 'COMPLICACIONES'),
  (1649, 'Plan de Trabajo', 'PLAN_TRABAJO'),
  (1657, 'Tipo de cirugía', 'TIPO_CIRUGIA'),
  (1809, 'Especificar - Largo', 'ESPECIFICAR_LARGO'),
  (1955, 'Diagnóstico Oncológico', 'DIAGNOSTICO_ONCOLOGICO'),
  (1956, 'Estadío', 'ESTADIO'),
  (1957, 'Clasificación', 'CLASIFICACION'),
  (1958, 'Subclasificación', 'SUBCLASIFICACION'),
  (1959, 'TNM', 'TNM'),
  (1960, 'Enfermedad oncológica activa', 'ENFERMEDAD_ONCOLOGICA_ACTIVA'),
  (2013, 'Wong Baker SQL', 'WONG_BAKER_SQL'),
  (2015, 'Humpty - Dumpty SQL', 'HUMPTY_DUMPTY_SQL'),
  (2133, 'Pronostico2', 'PRONOSTICO2'),
  (2145, 'Perfusionista 2 Texto Libre', 'PERFUSIONISTA2_TEXTO_LIBRE'),
  (2151, 'Antecedentes Ginecológicos 2', 'ANTECEDENTES_GINECOLOGICOS2'),
  (2158, 'Exploracion Fisica RTF', 'EXPLORACION_FISICA_RTF'),
  (2159, 'Hora de Inicio Cirugia', 'HORA_INICIO_CIRUGIA'),
  (2160, 'Hora de Termiino Cirugia', 'HORA_TERMINO_CIRUGIA'),
  (2162, 'Tiempo Operatorio Corto', 'TIEMPO_OPERATORIO_CORTO'),
  (2163, 'Administración de Esquema Terapeútico RTF', 'ADMINISTRACION_ESQUEMA_TERAPEUTICO'),
  (2165, 'Recursos de la Cirugia', 'RECURSOS_CIRUGIA'),
  (2166, 'Tipo de Anestesia 3', 'TIPO_ANESTESIA3'),
  (2168, 'Clasificacion de Cirugia', 'CLASIFICACION_CIRUGIA'),
  (2169, 'Diagnosticos', 'DIAGNOSTICO'),
  (2170, 'Cirugias', 'CIRUGIAS'),
  (2176, 'Relato de la Enfermedad RTF', 'RELATO_ENFERMEDAD_RTF'),
  (2229, 'Diagnostico de Esquema Quimioterapia', 'DIAGNOSTICO_ESQUEMA_QUIMIOTERAPIA'),
  (2249, 'Detalle de Educación Largo', 'DETALLE_EDUCACION_LARGO'),
  (2257, 'Otros Recursos Humanos', 'OTROS_RECURSOS_HUMANOS'),
  (2271, 'Paridad_1', 'PARIDAD1'),
  (3015, 'Cirugias_Programadas', 'CIRUGIAS_PROGRAMADAS'),
  (3141, 'Cirugias_Realizadas', 'CIRUGIAS_REALIZADAS'),
  (3142, 'Hallazgos Operatorios', 'HALLAZGOS_OPERATORIOS'),
  (3143, 'Complicaciones Intra-Operatoirias', 'COMPLICACIONES_INTRA_OPERATORIAS'),
  (3144, 'Tecnica Operatoria', 'TECNICA_OPERATORIA'),
  (3145, 'Sangrado Intra-Operatorio', 'SANGRADO_INFRA_OPERATORIO'),
  (3146, 'Pieza Operatoria', 'PIEZA_OPERATORIA'),
  (3147, 'Muestra Quirurgica', 'MUESTRA_QUIRURGICA'),
  (3148, 'Equipos y Materiales Utilizados', 'EQUIPOS_MATERIALES_UTILIZADOS'),
  (3152, 'Nombre de Recurso', 'NOMBRE_RECURSO'),
  (3153, 'Antecedentes Epidemiológicos / Ocupacionales', 'ANTECEDENTES_EPIDEMIOLOGICOS_OCUPACIONALES'),
  (3253, 'Tipo de Cirugia2', 'TIPO_CIRUGIA2'),
  (3365, 'Bomba elastomérica', 'BOMBA_ELASTOMERICA'),
  (3366, 'T', 'T'),
  (3367, 'N', 'N'),
  (3368, 'M', 'M'),
  (3370, 'Complicaciones', 'COMPLICACIONES'),
  (3371, 'Tipo de paciente', 'TIPO_PACIENTE');